name: Checks
on:
  pull_request:
  types: [opened, synchronize]

jobs:
  checks:
  runs-on:ubuntu-latest

  steps:
  - name: "Checkout"
    uses: "actions/checkout@v2"
    with:
     token: ${{ secrets.NESTMICROSERVIES }
  
  - name: "Use NodeJS 20"
    uses: "actions/checkout@v4"
    with:
      node-version: "20"
       registry-url: https://registry.npmjs.org/
  
  - name: "Setup npm"
    run: 
  
  - name: "Install dependencies"
    run: |
      npm ci
      npx lerna bootstrap
    
  - name: "Run tests"
    run: |
      npx lerna exec npm run test 
    

